#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSHOP_RUNTIME_PLATFORM_VERSION=$(python3 "$SCRIPT_DIR/../runtime_deploy.py" --print-platform)
export WORKSHOP_RUNTIME_PLATFORM_VERSION

echo "========================================="
echo " AgentCore MCP - Full Deployment"
echo "========================================="
echo ""
echo "This build, push, and Runtime deployment takes several minutes. Do not interrupt it."
echo ""

"$SCRIPT_DIR/deploy-credential.sh"
echo ""
echo "-----------------------------------------"
echo ""
"$SCRIPT_DIR/deploy-runtime.sh"
echo ""
echo "-----------------------------------------"
echo ""
"$SCRIPT_DIR/deploy-gateway.sh"
echo ""
echo "-----------------------------------------"
echo ""
"$SCRIPT_DIR/verify-gateway.sh"

echo ""
echo "========================================="
echo " Deployment Complete"
echo "========================================="
echo ""
source "$SCRIPT_DIR/config.sh"
echo "Gateway URL: $(state_get 'gateway_url')"
echo "Runtime ARN: $(state_get 'runtime_arn')"
echo "State file:  ${STATE_FILE}"
echo ""
# What was created, and the read-only commands that show it without these scripts.
GATEWAY_ID="$(state_get 'gateway_id')"
echo "What this created:"
echo "  Secrets Manager secret  $(state_get 'github_app_secret_arn')"
echo "                          the GitHub App credentials; the MCP Runtime's role reads them"
echo "  AgentCore Runtime       $(state_get 'runtime_arn')"
echo "                          the GitHub MCP server (MCP protocol), role $(state_get 'iam_role_name')"
echo "  AgentCore Gateway       ${GATEWAY_ID} (callers sign with AWS IAM, SigV4)"
echo "                          one URL for GitHub tools; callers never hold a GitHub key"
echo "  Gateway target          $(state_get 'gateway_target_name')"
echo "                          routes tool calls to the Runtime, signed with the Gateway's role $(state_get 'gateway_role_name')"
echo "See them yourself (read-only):"
echo "  aws bedrock-agentcore-control get-gateway --gateway-identifier ${GATEWAY_ID} --region ${AWS_REGION}"
echo "  aws bedrock-agentcore-control list-gateway-targets --gateway-identifier ${GATEWAY_ID} --region ${AWS_REGION}"
echo "  aws bedrock-agentcore-control get-agent-runtime --agent-runtime-id $(state_get 'runtime_id') --region ${AWS_REGION}"
